# Generated by Django 4.2.4 on 2023-09-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='balance',
            field=models.IntegerField(verbose_name='0'),
        ),
    ]
