# Generated by Django 4.2.4 on 2023-09-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_login_password_alter_register_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='accno',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
